// apps/web/src/app/signup/page.tsx
'use client';

import { Button, Input } from '@heroui/react';
import { zodResolver } from '@hookform/resolvers/zod';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';

const signupSchema = z.object({
  email: z.string().email('Invalid email address'),
  password: z.string().min(8, 'Password must be at least 8 characters'),
  inviteCode: z.string().min(1, 'Invite code is required'),
});

type SignupForm = z.infer<typeof signupSchema>;

export default function SignupPage() {
  const router = useRouter();
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<SignupForm>({
    resolver: zodResolver(signupSchema),
  });

  const onSubmit = async (data: SignupForm) => {
    setIsLoading(true);
    setError(null);

    try {
      const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8787';
      const response = await fetch(`${apiUrl}/api/auth/signup`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include', // Important for cookies
        body: JSON.stringify({
          email: data.email,
          password: data.password,
          inviteCode: data.inviteCode.toUpperCase(),
        }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Signup failed');
      }

      // Redirect to dashboard/home
      router.push('/');
      router.refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800">
      <div className="w-full max-w-md space-y-8 rounded-2xl bg-white p-8 shadow-xl dark:bg-gray-800">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Create Account</h1>
          <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
            Sign up with your invite code
          </p>
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          {error && (
            <div className="rounded-lg bg-red-50 p-4 text-sm text-red-800 dark:bg-red-900/20 dark:text-red-400">
              {error}
            </div>
          )}

          <Input
            {...register('email')}
            type="email"
            label="Email"
            placeholder="you@example.com"
            variant="bordered"
            isInvalid={!!errors.email}
            errorMessage={errors.email?.message}
            disabled={isLoading}
          />

          <Input
            {...register('password')}
            type="password"
            label="Password"
            placeholder="••••••••"
            variant="bordered"
            isInvalid={!!errors.password}
            errorMessage={errors.password?.message}
            disabled={isLoading}
            description="Must be at least 8 characters"
          />

          <Input
            {...register('inviteCode')}
            type="text"
            label="Invite Code"
            placeholder="INVITE-XXXX-XXXX"
            variant="bordered"
            isInvalid={!!errors.inviteCode}
            errorMessage={errors.inviteCode?.message}
            disabled={isLoading}
            description="Enter your invite code to create an account"
          />

          <Button type="submit" color="primary" size="lg" className="w-full" isLoading={isLoading}>
            Create Account
          </Button>
        </form>

        <div className="text-center text-sm">
          <span className="text-gray-600 dark:text-gray-400">Already have an account? </span>
          <a href="/login" className="font-medium text-primary hover:underline">
            Sign in
          </a>
        </div>
      </div>
    </div>
  );
}

// apps/web/src/routes/signup/+page.svelte
<script lang="ts">
import { goto } from '$app/navigation';
import { signup } from '$lib/auth';

let email = $state('');
let password = $state('');
let inviteCode = $state('');
let error = $state<string | null>(null);
let isLoading = $state(false);

async function handleSubmit(event: SubmitEvent) {
  event.preventDefault();
  isLoading = true;
  error = null;

  try {
    await signup(email, password, inviteCode);
    goto('/');
  } catch (err) {
    error = err instanceof Error ? err.message : 'An error occurred';
  } finally {
    isLoading = false;
  }
}
</script>

<div
	class="flex min-h-screen items-center justify-center bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800"
>
	<div class="w-full max-w-md space-y-8 rounded-2xl bg-white p-8 shadow-xl dark:bg-gray-800">
		<div>
			<h1 class="text-3xl font-bold text-gray-900 dark:text-white">Create Account</h1>
			<p class="mt-2 text-sm text-gray-600 dark:text-gray-400">Sign up with your invite code</p>
		</div>

		<form onsubmit={handleSubmit} class="space-y-6">
			{#if error}
				<div
					class="rounded-lg bg-red-50 p-4 text-sm text-red-800 dark:bg-red-900/20 dark:text-red-400"
				>
					{error}
				</div>
			{/if}

			<div>
				<label for="email" class="block text-sm font-medium text-gray-700 dark:text-gray-300">
					Email
				</label>
				<input
					id="email"
					type="email"
					bind:value={email}
					placeholder="you@example.com"
					required
					disabled={isLoading}
					class="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-3 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20 disabled:opacity-50 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
				/>
			</div>

			<div>
				<label for="password" class="block text-sm font-medium text-gray-700 dark:text-gray-300">
					Password
				</label>
				<input
					id="password"
					type="password"
					bind:value={password}
					placeholder="••••••••"
					required
					minlength="8"
					disabled={isLoading}
					class="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-3 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20 disabled:opacity-50 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
				/>
				<p class="mt-1 text-xs text-gray-500 dark:text-gray-400">
					Must be at least 8 characters
				</p>
			</div>

			<div>
				<label for="inviteCode" class="block text-sm font-medium text-gray-700 dark:text-gray-300">
					Invite Code
				</label>
				<input
					id="inviteCode"
					type="text"
					bind:value={inviteCode}
					placeholder="INVITE-XXXX-XXXX"
					required
					disabled={isLoading}
					class="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-3 uppercase focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20 disabled:opacity-50 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
				/>
				<p class="mt-1 text-xs text-gray-500 dark:text-gray-400">
					Enter your invite code to create an account
				</p>
			</div>

			<button
				type="submit"
				disabled={isLoading}
				class="w-full rounded-lg bg-blue-600 px-4 py-3 font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-50 transition-colors"
			>
				{#if isLoading}
					<span class="flex items-center justify-center gap-2">
						<span
							class="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent"
						></span>
						Creating account...
					</span>
				{:else}
					Create Account
				{/if}
			</button>
		</form>

		<div class="text-center text-sm">
			<span class="text-gray-600 dark:text-gray-400">Already have an account? </span>
			<a href="/login" class="font-medium text-blue-600 hover:underline dark:text-blue-400">
				Sign in
			</a>
		</div>
	</div>
</div>
